using EventImageServer.Contexts;
using EventImageServer.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;

namespace EventImageServer.Controllers
{
    // Public, unauthenticated endpoints used by guests to view/respond to their
    // RSVP via the secure per-guest token generated by SeatingController.
    [Route("[controller]")]
    [ApiController]
    [AllowAnonymous]
    [EnableRateLimiting("rsvp")]
    public class RsvpController : ControllerBase
    {
        private readonly AppDbContext _dbContext;

        public RsvpController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public class RsvpResponseRequest
        {
            public RsvpStatus Status { get; set; }
            public int? ConfirmedCount { get; set; }
            public Dictionary<string, int>? MealCounts { get; set; }
            public string? Note { get; set; }
        }

        // Guest media upload limits (wedding-day photo/video sharing feature).
        private const int MaxPhotos = 10;
        private const int MaxVideos = 3;
        private const long MaxPhotoBytes = 10L * 1024 * 1024; // 10 MB
        private const long MaxVideoBytes = 100L * 1024 * 1024; // 100 MB
        private static readonly HashSet<string> PhotoExtensions = new(StringComparer.OrdinalIgnoreCase)
        {
            ".jpg", ".jpeg", ".png", ".gif", ".webp", ".heic"
        };
        private static readonly HashSet<string> VideoExtensions = new(StringComparer.OrdinalIgnoreCase)
        {
            ".mp4", ".webm", ".ogg", ".mov"
        };

        // Uploads are only allowed from the wedding day/time itself through one
        // grace day afterward (guests are often uploading the morning after).
        // EventDate carries both the date and time-of-day the owner set.
        // Uploads are strictly blocked before the wedding moment.
        private static bool IsUploadWindowOpen(Users? owner)
        {
            if (owner?.EventDate == null)
            {
                return false;
            }

            var now = DateTime.Now;
            var start = owner.EventDate.Value;
            var end = start.AddDays(1);
            
            // Only open if we're at or past the start time, and before the end time
            return now >= start && now <= end;
        }

        // RSVP answers are locked for the entire calendar day of the wedding
        // onward — not just from the exact hour the ceremony starts. Guests
        // shouldn't be able to change their attendance/meal/note the morning of
        // (or after) the wedding, even before the precise upload window opens.
        private static bool IsRsvpLocked(Users? owner)
        {
            if (owner?.EventDate == null)
            {
                return false;
            }

            return DateTime.Now.Date >= owner.EventDate.Value.Date;
        }

        // Returns the guest's RSVP details for the given token, and marks the
        // link as opened (first view only) as a side-effect.
        [HttpGet("{token}")]
        public async Task<IActionResult> GetRsvp(string token)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var guest = _dbContext.Guests.FirstOrDefault(g => g.RsvpToken == token);
            if (guest == null)
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var owner = _dbContext.Clients.FirstOrDefault(u => u.Id == guest.OwnerId);
            var deadline = owner?.RsvpDeadline;
            var deadlinePassed = deadline.HasValue && DateTime.UtcNow > deadline.Value;

            if (guest.RsvpOpenedAt == null)
            {
                guest.RsvpOpenedAt = DateTime.UtcNow;
                await _dbContext.SaveChangesAsync();
            }

            return Ok(new
            {
                name = guest.Name,
                numberOfGuests = guest.NumberOfGuests,
                status = guest.RsvpStatus,
                confirmedCount = guest.ConfirmedCount,
                mealCounts = guest.MealCounts,
                note = guest.RsvpNote,
                deadline,
                deadlinePassed,
                optedOut = guest.OptedOut,
                eventDate = owner?.EventDate,
                uploadWindowOpen = IsUploadWindowOpen(owner),
                rsvpLocked = IsRsvpLocked(owner),
                photosUploaded = guest.GuestPhotoUploadCount,
                videosUploaded = guest.GuestVideoUploadCount,
                maxPhotos = MaxPhotos,
                maxVideos = MaxVideos
            });
        }

        // Records the guest's RSVP response for the given token.
        [HttpPost("{token}")]
        public async Task<IActionResult> SubmitRsvp(string token, [FromBody] RsvpResponseRequest request)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var guest = _dbContext.Guests.FirstOrDefault(g => g.RsvpToken == token);
            if (guest == null)
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            if (guest.OptedOut)
            {
                return StatusCode(409, new { message = "This guest has opted out of communications." });
            }

            var owner = _dbContext.Clients.FirstOrDefault(u => u.Id == guest.OwnerId);
            if (owner?.RsvpDeadline.HasValue == true && DateTime.UtcNow > owner.RsvpDeadline.Value)
            {
                return StatusCode(410, new { message = "The RSVP deadline has passed." });
            }

            // RSVP responses are locked for the whole calendar day of the wedding
            // (and after) — at that point guests can only share photos/videos, not
            // change their attendance/meal/note answers.
            if (IsRsvpLocked(owner))
            {
                return StatusCode(409, new { message = "RSVP responses are closed on the wedding day. You can still share photos and videos!" });
            }

            if (!Enum.IsDefined(typeof(RsvpStatus), request.Status))
            {
                return BadRequest(new { message = "Invalid RSVP status." });
            }

            // Guests may adjust their attending count freely (e.g. a +1 who wasn't
            // originally invited with a full party size) — only a sane absolute
            // upper bound is enforced here, not the originally invited count. The
            // owner can then sync the official party size to match, if desired,
            // from the Guests page.
            const int maxConfirmedCount = 50;
            if (request.ConfirmedCount.HasValue &&
                (request.ConfirmedCount.Value < 0 || request.ConfirmedCount.Value > maxConfirmedCount))
            {
                return BadRequest(new { message = $"Confirmed count must be between 0 and {maxConfirmedCount}." });
            }

            // A guest's free-text note has no real reason to be huge; cap it well
            // above any reasonable dietary/logistics note to avoid abuse.
            const int maxNoteLength = 1000;
            if (request.Note != null && request.Note.Length > maxNoteLength)
            {
                return BadRequest(new { message = $"Note must be {maxNoteLength} characters or fewer." });
            }

            guest.RsvpStatus = request.Status;
            guest.ConfirmedCount = request.Status == RsvpStatus.Confirmed
                ? (request.ConfirmedCount ?? guest.NumberOfGuests)
                : request.ConfirmedCount;
            guest.RsvpRespondedAt = DateTime.UtcNow;
            guest.MealCounts = request.Status == RsvpStatus.Declined ? null : request.MealCounts;
            guest.RsvpNote = request.Note;

            // A declined guest isn't coming, so they shouldn't occupy a seat or
            // count toward the party-size/capacity totals — clear their table
            // assignment and zero their party size.
            if (request.Status == RsvpStatus.Declined)
            {
                guest.TableId = null;
                guest.NumberOfGuests = 0;
            }

            await _dbContext.SaveChangesAsync();

            return Ok(new
            {
                status = guest.RsvpStatus,
                confirmedCount = guest.ConfirmedCount
            });
        }

        // Accepts a single photo/video from a guest via their RSVP link. Only
        // available on the wedding day (+1 grace day), independent of the RSVP
        // deadline. Saved into the owner's existing gallery folder so it shows
        // up alongside the owner's own uploads, with a per-guest quota tracked
        // on the Guest row (10 photos / 3 videos).
        [HttpPost("{token}/media")]
        [RequestSizeLimit(MaxVideoBytes)]
        public async Task<IActionResult> UploadGuestMedia(string token, IFormFile file)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var guest = _dbContext.Guests.FirstOrDefault(g => g.RsvpToken == token);
            if (guest == null)
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var owner = _dbContext.Clients.FirstOrDefault(u => u.Id == guest.OwnerId);
            if (!IsUploadWindowOpen(owner))
            {
                return StatusCode(403, new { message = "Photo/video uploads are only available on the wedding day." });
            }

            if (file == null || file.Length == 0)
            {
                return BadRequest(new { message = "No file uploaded." });
            }

            var ext = Path.GetExtension(file.FileName);
            var isPhoto = PhotoExtensions.Contains(ext);
            var isVideo = VideoExtensions.Contains(ext);
            if (!isPhoto && !isVideo)
            {
                return BadRequest(new { message = "Unsupported file type." });
            }

            if (isPhoto && file.Length > MaxPhotoBytes)
            {
                return BadRequest(new { message = "Photos must be 10MB or smaller." });
            }
            if (isVideo && file.Length > MaxVideoBytes)
            {
                return BadRequest(new { message = "Videos must be 100MB or smaller." });
            }

            if (isPhoto && guest.GuestPhotoUploadCount >= MaxPhotos)
            {
                return StatusCode(409, new { message = $"You've already uploaded the maximum of {MaxPhotos} photos." });
            }
            if (isVideo && guest.GuestVideoUploadCount >= MaxVideos)
            {
                return StatusCode(409, new { message = $"You've already uploaded the maximum of {MaxVideos} videos." });
            }

            var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "UploadedImages", guest.OwnerId ?? string.Empty);
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            var fileName = $"{Guid.NewGuid()}{ext}";
            var filePath = Path.Combine(folderPath, fileName);
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            if (isPhoto)
            {
                guest.GuestPhotoUploadCount += 1;
            }
            else
            {
                guest.GuestVideoUploadCount += 1;
            }

            var media = new GuestMedia
            {
                GuestId = guest.GuestId,
                OwnerId = guest.OwnerId,
                FileName = fileName,
                MediaType = isPhoto ? "image" : "video"
            };
            _dbContext.GuestMedia.Add(media);

            await _dbContext.SaveChangesAsync();

            return Ok(new
            {
                id = media.GuestMediaId,
                url = $"/UploadedImages/{guest.OwnerId}/{fileName}",
                type = isPhoto ? "image" : "video",
                photosUploaded = guest.GuestPhotoUploadCount,
                videosUploaded = guest.GuestVideoUploadCount,
                maxPhotos = MaxPhotos,
                maxVideos = MaxVideos
            });
        }

        // Returns the media this specific guest has uploaded via their RSVP
        // link, so the guest page can render only their own photos/videos (not
        // every guest's) with the ability to remove and re-upload.
        [HttpGet("{token}/media")]
        public IActionResult GetGuestMedia(string token)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var guest = _dbContext.Guests.FirstOrDefault(g => g.RsvpToken == token);
            if (guest == null)
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var media = _dbContext.GuestMedia
                .Where(m => m.GuestId == guest.GuestId)
                .OrderBy(m => m.CreatedAt)
                .Select(m => new
                {
                    id = m.GuestMediaId,
                    url = $"/UploadedImages/{guest.OwnerId}/{m.FileName}",
                    type = m.MediaType
                })
                .ToList();

            return Ok(media);
        }

        // Lets a guest remove one of their own uploads (e.g. to swap it for a
        // better shot) — deletes the file from disk, the tracking row, and frees
        // up one slot in their photo/video quota. Only the uploading guest's own
        // token can delete their own media; ownership is checked via GuestId.
        [HttpDelete("{token}/media/{mediaId}")]
        public async Task<IActionResult> DeleteGuestMedia(string token, int mediaId)
        {
            if (string.IsNullOrWhiteSpace(token))
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var guest = _dbContext.Guests.FirstOrDefault(g => g.RsvpToken == token);
            if (guest == null)
            {
                return NotFound(new { message = "Invalid RSVP link." });
            }

            var media = _dbContext.GuestMedia.FirstOrDefault(m => m.GuestMediaId == mediaId && m.GuestId == guest.GuestId);
            if (media == null)
            {
                return NotFound(new { message = "Media not found." });
            }

            var folderPath = Path.Combine(Directory.GetCurrentDirectory(), "UploadedImages", guest.OwnerId ?? string.Empty);
            var filePath = Path.Combine(folderPath, media.FileName);
            var fullFolderPath = Path.GetFullPath(folderPath);
            var fullFilePath = Path.GetFullPath(filePath);
            if (fullFilePath.StartsWith(fullFolderPath) && System.IO.File.Exists(fullFilePath))
            {
                System.IO.File.Delete(fullFilePath);
            }

            if (media.MediaType == "image")
            {
                guest.GuestPhotoUploadCount = Math.Max(0, guest.GuestPhotoUploadCount - 1);
            }
            else
            {
                guest.GuestVideoUploadCount = Math.Max(0, guest.GuestVideoUploadCount - 1);
            }

            _dbContext.GuestMedia.Remove(media);
            await _dbContext.SaveChangesAsync();

            return Ok(new
            {
                photosUploaded = guest.GuestPhotoUploadCount,
                videosUploaded = guest.GuestVideoUploadCount,
                maxPhotos = MaxPhotos,
                maxVideos = MaxVideos
            });
        }
    }
}
